### ISSUE TITLE
Add support for EML Multiplex

### ISSUE THREAD

**Issue by ferrenb** [awslabs/aws-media-services-application-mapper#75] opened 2020-01-06 21:02 UTC
Multiplex would be similar to how EML Input and Channel are represented in the UI. Multiplex appear to have it's own alerts/events - additional support for those to be polled by the platform, ideally.

**Comment by JimTharioAmazon** [comment] 2020-01-07 19:17
Duplicate of #68

**Closed by JimTharioAmazon** 2020-01-07 19:17 UTC
